name: appconfigdata
defaultCommand: ''
commands:
- name: GetLatestConfiguration
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Appconfigdata
  rerunOnBack: false
  favouritable: true
- name: StartConfigurationSession
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
