name: application-signals
defaultCommand: list-grouping-attribute-definitions
commands:
- name: list-grouping-attribute-definitions
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: GroupingAttributeDefinitions
  rerunOnBack: false
  favouritable: true
- name: list-service-level-objectives
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: SloSummaries
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
