name: application-autoscaling
defaultCommand: ''
commands:
- name: ListTagsForResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tagsforresources
  rerunOnBack: false
  favouritable: true
- name: DescribeScalableTargets
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: DescribeScalingActivities
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: DescribeScalingPolicies
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: DescribeScheduledActions
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: GetPredictiveScalingForecast
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: DeregisterScalableTarget
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: RegisterScalableTarget
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Application-Autoscaling
  rerunOnBack: false
  favouritable: true
- name: TagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: UntagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
