name: codeguru-security
defaultCommand: list-scans
commands:
- name: list-scans
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: summaries
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: get-account-configuration
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: encryptionConfig
  rerunOnBack: false
  favouritable: true
