name: compute-optimizer-automation
defaultCommand: list-accounts
commands:
- name: list-accounts
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: accounts
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-automation-event-summaries
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: automationEventSummaries
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-automation-events
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: automationEvents
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-automation-rules
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: automationRules
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-recommended-action-summaries
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: recommendedActionSummaries
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-recommended-actions
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: recommendedActions
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
