name: config
defaultCommand: list-configuration-recorders
commands:
- name: list-configuration-recorders
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConfigurationRecorderSummaries
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: list-conformance-pack-compliance-scores
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConformancePackComplianceScores
  rerunOnBack: false
  favouritable: true
- name: list-resource-evaluations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ResourceEvaluations
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: list-stored-queries
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: StoredQueryMetadata
  rerunOnBack: false
  favouritable: true
- name: describe-aggregation-authorizations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: AggregationAuthorizations
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-compliance-by-config-rule
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ComplianceByConfigRules
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-compliance-by-resource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ComplianceByResources
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-config-rule-evaluation-status
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConfigRulesEvaluationStatus
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-config-rules
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConfigRules
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-configuration-aggregators
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConfigurationAggregators
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-configuration-recorder-status
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConfigurationRecordersStatus
  rerunOnBack: false
  favouritable: true
- name: describe-configuration-recorders
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConfigurationRecorders
  rerunOnBack: false
  favouritable: true
- name: describe-conformance-pack-status
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConformancePackStatusDetails
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-conformance-packs
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ConformancePackDetails
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-delivery-channel-status
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: DeliveryChannelsStatus
  rerunOnBack: false
  favouritable: true
- name: describe-delivery-channels
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: DeliveryChannels
  rerunOnBack: false
  favouritable: true
- name: describe-organization-config-rule-statuses
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: OrganizationConfigRuleStatuses
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-organization-config-rules
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: OrganizationConfigRules
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-organization-conformance-pack-statuses
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: OrganizationConformancePackStatuses
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
- name: describe-organization-conformance-packs
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: OrganizationConformancePacks
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: NextToken
