name: config
defaultCommand: ''
commands:
- name: ListAggregateDiscoveredResources
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: aggregatediscoveredresource
  rerunOnBack: false
  favouritable: true
- name: ListConfigurationRecorders
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: configurationrecorder
  rerunOnBack: false
  favouritable: true
- name: ListConformancePackComplianceScores
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: conformancepackcompliancescore
  rerunOnBack: false
  favouritable: true
- name: ListDiscoveredResources
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: discoveredresource
  rerunOnBack: false
  favouritable: true
- name: ListResourceEvaluations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: resourceevaluation
  rerunOnBack: false
  favouritable: true
- name: ListStoredQueries
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: storedquerie
  rerunOnBack: false
  favouritable: true
- name: ListTagsForResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tagsforresources
  rerunOnBack: false
  favouritable: true
- name: DescribeAggregateComplianceByConfigRules
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeAggregateComplianceByConformancePacks
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeAggregationAuthorizations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeComplianceByConfigRule
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeComplianceByResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConfigRuleEvaluationStatus
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConfigRules
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConfigurationAggregatorSourcesStatus
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConfigurationAggregators
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConfigurationRecorderStatus
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConfigurationRecorders
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConformancePackCompliance
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
- name: DescribeConformancePackStatus
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Config
  rerunOnBack: false
  favouritable: true
