name: emr-serverless
defaultCommand: ''
commands:
- name: ListApplications
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: application
  rerunOnBack: false
  favouritable: true
- name: ListJobRunAttempts
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: jobrunattempt
  rerunOnBack: false
  favouritable: true
- name: ListJobRuns
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: jobrun
  rerunOnBack: false
  favouritable: true
- name: ListTagsForResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tagsforresources
  rerunOnBack: false
  favouritable: true
- name: GetApplication
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Emr-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetDashboardForJobRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Emr-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetJobRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Emr-Serverless
  rerunOnBack: false
  favouritable: true
- name: CancelJobRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: StartApplication
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: StartJobRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: StopApplication
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: TagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: UntagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
