name: mwaa-serverless
defaultCommand: ''
commands:
- name: ListTagsForResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tagsforresources
  rerunOnBack: false
  favouritable: true
- name: ListTaskInstances
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: taskinstance
  rerunOnBack: false
  favouritable: true
- name: ListWorkflowRuns
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: workflowrun
  rerunOnBack: false
  favouritable: true
- name: ListWorkflowVersions
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: workflowversion
  rerunOnBack: false
  favouritable: true
- name: ListWorkflows
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: workflow
  rerunOnBack: false
  favouritable: true
- name: GetTaskInstance
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Mwaa-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetWorkflow
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Mwaa-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetWorkflowRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Mwaa-Serverless
  rerunOnBack: false
  favouritable: true
- name: StartWorkflowRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: StopWorkflowRun
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: TagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
- name: UntagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
