name: redshift-serverless
defaultCommand: ''
commands:
- name: ListCustomDomainAssociations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: customdomainassociation
  rerunOnBack: false
  favouritable: true
- name: ListEndpointAccess
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: endpointacces
  rerunOnBack: false
  favouritable: true
- name: ListManagedWorkgroups
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: managedworkgroup
  rerunOnBack: false
  favouritable: true
- name: ListNamespaces
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: namespace
  rerunOnBack: false
  favouritable: true
- name: ListRecoveryPoints
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: recoverypoint
  rerunOnBack: false
  favouritable: true
- name: ListReservationOfferings
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: reservationoffering
  rerunOnBack: false
  favouritable: true
- name: ListReservations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: reservation
  rerunOnBack: false
  favouritable: true
- name: ListScheduledActions
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: scheduledaction
  rerunOnBack: false
  favouritable: true
- name: ListSnapshotCopyConfigurations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: snapshotcopyconfiguration
  rerunOnBack: false
  favouritable: true
- name: ListSnapshots
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: snapshot
  rerunOnBack: false
  favouritable: true
- name: ListTableRestoreStatus
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tablerestorestatu
  rerunOnBack: false
  favouritable: true
- name: ListTagsForResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tagsforresources
  rerunOnBack: false
  favouritable: true
- name: ListTracks
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: track
  rerunOnBack: false
  favouritable: true
- name: ListUsageLimits
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: usagelimit
  rerunOnBack: false
  favouritable: true
- name: ListWorkgroups
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: workgroup
  rerunOnBack: false
  favouritable: true
- name: GetCredentials
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Redshift-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetCustomDomainAssociation
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Redshift-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetEndpointAccess
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Redshift-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetIdentityCenterAuthToken
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Redshift-Serverless
  rerunOnBack: false
  favouritable: true
- name: GetNamespace
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Redshift-Serverless
  rerunOnBack: false
  favouritable: true
