name: route53-recovery-control-config
defaultCommand: ''
commands:
- name: ListAssociatedRoute53HealthChecks
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: associatedroute53healthcheck
  rerunOnBack: false
  favouritable: true
- name: ListClusters
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: cluster
  rerunOnBack: false
  favouritable: true
- name: ListControlPanels
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: controlpanel
  rerunOnBack: false
  favouritable: true
- name: ListRoutingControls
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: routingcontrol
  rerunOnBack: false
  favouritable: true
- name: ListSafetyRules
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: safetyrule
  rerunOnBack: false
  favouritable: true
- name: ListTagsForResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: tagsforresources
  rerunOnBack: false
  favouritable: true
- name: DescribeCluster
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Route53-Recovery-Control-Config
  rerunOnBack: false
  favouritable: true
- name: DescribeControlPanel
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Route53-Recovery-Control-Config
  rerunOnBack: false
  favouritable: true
- name: DescribeRoutingControl
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Route53-Recovery-Control-Config
  rerunOnBack: false
  favouritable: true
- name: DescribeSafetyRule
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Route53-Recovery-Control-Config
  rerunOnBack: false
  favouritable: true
- name: GetResourcePolicy
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: Route53-Recovery-Control-Config
  rerunOnBack: false
  favouritable: true
- name: TagResource
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: contentView
  showJsonViewer: true
  parse:
    type: object
    attributeName: ''
  rerunOnBack: false
  favouritable: true
