name: taxsettings
defaultCommand: list-supplemental-tax-registrations
commands:
- name: list-supplemental-tax-registrations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: taxRegistrations
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-tax-exemptions
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: taxExemptionDetailsMap
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: list-tax-registrations
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: accountDetails
  rerunOnBack: false
  favouritable: true
  pagination:
    enabled: true
    nextTokenParam: --next-token
    nextTokenJsonPath: nextToken
- name: get-tax-exemption-types
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: taxExemptionTypes
  rerunOnBack: false
  favouritable: true
- name: get-tax-registration
  arguments:
  - --output
  - json
  - --cli-read-timeout
  - '10'
  - --cli-connect-timeout
  - '5'
  view: tableView
  showJsonViewer: true
  parse:
    type: object
    attributeName: taxRegistration
  rerunOnBack: false
  favouritable: true
